#pragma once

#include <clean-core/span.hh>
#include <clean-core/string_view.hh>

#include <typed-geometry/tg.hh>

#include <phantasm-hardware-interface/commands.hh>

#include <phantasm-renderer/common/growing_writer.hh>
#include <phantasm-renderer/default_config.hh>
#include <phantasm-renderer/format.hh>

#include <phantasm-renderer/resource_types.hh>

#include "ComputePipeline.hh"
#include "Pass.hh"

namespace pr
{
class Frame
{
public:
    // pass RAII API

    template <class... RTs>
    Pass render_to(RTs const&... targets) // TODO return
    {
        phi::cmd::begin_render_pass bcmd;
        // initialize command
        bcmd.set_null_depth_stencil();
        bcmd.viewport = tg::isize2(1 << 30, 1 << 30);

        // add targets
        (addRenderTarget(bcmd, targets), ...);

        // flush RT transitions generated by addRenderTarget
        flushPendingTransitions();

        // write begin_render_pass
        mWriter.add_command(bcmd);

        return {this};
    }

    // pipeline RAII API (compute only, graphics pipelines are in pr::Pass

    ComputePipeline pipeline(compute_pipeline_state const& compute_pipeline) { return {this, compute_pipeline.data._handle}; }

    // TODO: cache-access version

    void transition(buffer const& res, phi::resource_state target, phi::shader_stage_flags_t dependency = {});
    void transition(image const& res, phi::resource_state target, phi::shader_stage_flags_t dependency = {});
    void transition(render_target const& res, phi::resource_state target, phi::shader_stage_flags_t dependency = {});

    // commands

    void copy(buffer const& src, buffer const& dest, size_t src_offset = 0, size_t dest_offset = 0);

    void copy(buffer const& src, image const& dest, size_t src_offset = 0, unsigned dest_mip_index = 0, unsigned dest_array_index = 0);

    void copy(image const& src, image const& dest);

    void resolve(render_target const& src, image const& dest);

    // move-only type
public:
    Frame(Frame const&) = delete;
    Frame& operator=(Frame const&) = delete;
    Frame(Frame&& rhs) noexcept : mCtx(rhs.mCtx), mWriter(cc::move(rhs.mWriter)), mPendingTransitionCommand(rhs.mPendingTransitionCommand)
    {
        rhs.mCtx = nullptr;
    }

    Frame& operator=(Frame&& rhs) noexcept
    {
        if (this != &rhs)
        {
            mCtx = rhs.mCtx;
            mWriter = cc::move(rhs.mWriter);
            mPendingTransitionCommand = rhs.mPendingTransitionCommand;
            rhs.mCtx = nullptr;
        }

        return *this;
    }

    // private
private:
    void addRenderTarget(phi::cmd::begin_render_pass& bcmd, render_target const& rt);

    void transition(phi::handle::resource res, phi::resource_state target, phi::shader_stage_flags_t dependency = {});
    void flushPendingTransitions();

    // Pass-side API
private:
    friend class Pass;
    void passOnJoin(Pass const&);

    // Pipeline-side API
private:
    friend class PrimitivePipeline;
    friend class ComputePipeline;

    void pipelineOnDraw(phi::cmd::draw const& dcmd);
    void pipelineOnDispatch(phi::cmd::dispatch const& dcmd);


    // Context-side API
private:
    friend class Context;
    Frame(Context* ctx, size_t size) : mCtx(ctx), mWriter(size) {}

    std::byte* getMemory() const { return mWriter.buffer(); }
    size_t getSize() const { return mWriter.size(); }
    bool isEmpty() const { return mWriter.is_empty(); }

    // members
private:
    Context* mCtx;
    growing_writer mWriter;
    phi::cmd::transition_resources mPendingTransitionCommand;
};
}
